#!/bin/bash
url="http://planet.osm.org/replication/day/000/000/"
#url="http://planet.osm.org/redaction-period/day-replicate/000/000/"
sed 's/@//g' $4 > temp
sed 's/,/,/g' temp > u
rm temp
for i in $(seq $1 $2)
do	       
    if (($i<10)); then
        echo curl ${url}00$i.osc.gz -o "$i.osc.gz"
    fi
    if (($i<100)) && (($i>=10)); then
        echo curl ${url}0$i.osc.gz -o "$i.osc.gz"
    fi
    if (($i>=100)); then
        echo curl $url$i.osc.gz -o "$i.osc.gz"
    fi 
    echo "Processing file $i"
    echo  gzip -d $i.osc.gz
    echo ./osmconvert $i.osc -B=$3 -o=$i.o5m     
    echo  ./osmfilter $i.o5m --keep="highway=" -o=hig-$i.osm

    users=("$(cat u)")
    echo $users
    IFS="," read -ra STR_ARRAY <<< "$users"
    for j in "${STR_ARRAY[@]}"
    do
        echo ./osmfilter $i.osc --keep="\"@user=$j\"" -o=$i-$(echo $j | tr -d ' ').osm

    done
    
    #./osmfilter hig-$i.osm --keep="\"$(cat u)\"" -o=u-$i.osm
    echo ./osmconvert $i-* -o=u-$i.osm
    echo  node index.js --osmfile=u-$i.osm

    echo  ogr2ogr -f "PostgreSQL" PG:"host=localhost user=postgres dbname=dbprotiger" -append u-$i.geojson
    echo  rm $i.osc
    echo  rm $i.o5m
    echo  rm hig-$i.osm
    echo  rm u-$i.osm
    echo  rm u-$i.geojson
    echo "Process completed $i"

done
rm u



#osmconvert austria.o5m germany.o5m switzerland.o5m -o=dach.o5m

