#!/bin/bash
#url="http://planet.osm.org/replication/day/000/000/"
url="http://planet.openstreetmap.org/replication/hour/000/021/"
sed 's/@/@user=/g' $4 > temp
sed 's/,/ or /g' temp > u
rm temp
for i in $(seq $1 $2)
do	       
    if (($i<10)); then
        curl ${url}00$i.osc.gz -o "$i.osc.gz"
    fi
    if (($i<100)) && (($i>=10)); then
        curl ${url}0$i.osc.gz -o "$i.osc.gz"
    fi
    if (($i>=100)); then
        curl $url$i.osc.gz -o "$i.osc.gz"
    fi 
    echo "Processing file $i"
    gzip -d $i.osc.gz
    ./osmconvert $i.osc -B=$3 -o=$i.o5m     
    ./osmfilter $i.o5m --keep="highway=" -o=hig-$i.osm
    ./osmfilter hig-$i.osm --keep="\"$(cat u)\"" -o=u-$i.osm
    echo node index.js --osmfile=u-$i.osm
    ogr2ogr -f "PostgreSQL" PG:"host=localhost user=postgres dbname=dbtiger4" -append u-$i.geojson
    echo rm $i.osc
    echo rm $i.o5m
    echo rm hig-$i.osm
    echo rm u-$i.osm
    echo rm u-$i.geojson
    echo "Process completed $i"

done
rm u

