#!/bin/bash
npm install

psql -U postgres -c "create database dbprotiger";
psql -U postgres -d dbprotiger -f /usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql
psql -U postgres -d dbprotiger -f /usr/share/postgresql/9.3/contrib/postgis-2.1/spatial_ref_sys.sql
sudo apt-get install     cmake cmake-curses-gui make     libexpat1-dev     zlib1g-dev libbz2-dev
sudo apt-get install libsparsehash-dev     libboost-dev libboost-program-options-dev     libgdal-dev libgeos++-dev libproj-dev     doxygen graphviz
sudo add-apt-repository ppa:ubuntugis/ppa
sudo apt-get update
sudo apt-get install gdal-bin

git clone https://github.com/osmcode/libosmium.git
cd libosmium
mkdir build
cd build
cmake ..
make

cd 
cd extract-osm-edition/

#Ejecucion para establecer las columnas de la tabla
wget http://planet.osm.org/replication/day/000/001/080.osc.gz
gzip -d 080.osc.gz
./osmfilter 080.osc --keep="@user=Rub21" -o=Rub21.osm
node index.js --osmfile=Rub21.osm
ogr2ogr -f "PostgreSQL" PG:"host=localhost user=postgres dbname=dbprotiger" -append Rub21.geojson
rm 080.osc
rm Rub21.geojson
rm Rub21.osm

# Ejecucion  en gran escala
touch 1-200
touch 201-400
touch 401-600
touch 601-800
touch 801-999

nohup ./extract 1 200 us.poly users  > 1-200  2>&1 &
nohup ./extract 201 400 us.poly users  > 201-400  2>&1 &
nohup ./extract 401 600 us.poly users  > 401-600  2>&1 &
nohup ./extract 601 800 us.poly users  > 601-800 2>&1 &
nohup ./extract 801 999 us.poly users  > 801-999  2>&1 &

echo ./extract 0 999  us.poly users

