#!/bin/bash
npm install
#psql -U postgres -c "DROP database dbprotiger"
psql -U postgres -c "create database dbprotiger";
psql -U postgres -d dbprotiger -f /usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql
psql -U postgres -d dbprotiger -f /usr/share/postgresql/9.3/contrib/postgis-2.1/spatial_ref_sys.sql
sudo apt-get install     cmake cmake-curses-gui make     libexpat1-dev     zlib1g-dev libbz2-dev
sudo apt-get install libsparsehash-dev     libboost-dev libboost-program-options-dev     libgdal-dev libgeos++-dev libproj-dev     doxygen graphviz
sudo add-apt-repository ppa:ubuntugis/ppa
sudo apt-get update
sudo apt-get install gdal-bin

git clone https://github.com/osmcode/libosmium.git
cd libosmium
mkdir build
cd build
cmake ..
make

cd 
cd extract-osm-edition/

#Ejecucion para establecer las columnas de la tabla
wget http://planet.osm.org/replication/day/000/001/080.osc.gz
gzip -d 080.osc.gz
./osmconvert 080.osc -B=us.poly -o=080.osm 
./osmfilter 080.osm --keep="@user=PlaneMad" -o=PlaneMad.osm
node index.js --osmfile=PlaneMad.osm
ogr2ogr -f "PostgreSQL" PG:"host=localhost user=postgres dbname=dbprotiger" -append PlaneMad.geojson
rm 080.osc
rm PlaneMad.geojson
rm PlaneMad.osm

# Ejecucion  en gran escala
touch log-1-200
touch log-201-400
touch log-401-600
touch log-601-800
touch log-801-999

nohup ./extract 1 200 us.poly users  > log-1-200  2>&1 &
nohup ./extract 201 400 us.poly users  > log-201-400  2>&1 &
nohup ./extract 401 600 us.poly users  > log-401-600  2>&1 &
nohup ./extract 601 800 us.poly users  > log-601-800 2>&1 &
nohup ./extract 801 999 us.poly users  > log-801-999  2>&1 &

echo ./extract 0 999  us.poly users

